bump pandas to min version streamlit needs
ERROR: Cannot install -r /mount/src/breastcancer-predictor/requirements.txt (line 1) and pandas==1.0.5 because these package versions have conflicting dependencies.


The conflict is caused by:

    The user requested pandas==1.0.5

    streamlit 1.30.0 depends on pandas<3 and >=1.3.0